version: "3"
services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: poc
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  go_api:
    container_name: go_api
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data:
    name: db_data