---
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${file(sls/envs/config.${sls:stage}.yml):s3_bucket_name}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
              - POST
            AllowedOrigins:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::${file(sls/envs/config.${sls:stage}.yml):s3_bucket_name}/*"

Outputs:
  S3BucketNameOutputKey:
    Value: !Ref S3Bucket
    Description: S3 bucket for programs
    Export:
      Name: ${self:service}-${sls:stage}-programs-s3-bucket
