version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/music_licensing
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music_licensing
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: