version: '3.8'
services:
  web:
    container_name: web-fastapi
    build: .
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
      - .env.database
  db:
    container_name: db-fastapi
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - data-backups:/backups
    ports:
      - '5432:5432'
    env_file:
      - .env.database
  pgadmin:
    container_name: pgadmin-fastapi
    image: dpage/pgadmin4
    restart: always
    depends_on:
     - db
    ports:
      - "5050:80"
    env_file:
      - .env.database
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin-data:
  data-backups:
