"""Specified not nullable fields in Employee model

Revision ID: 11bd0063b0af
Revises: df8afbc693b9
Create Date: 2022-09-02 16:21:57.323377

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '11bd0063b0af'
down_revision = 'df8afbc693b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'first_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'last_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'address', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'city', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'state_province', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'country', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'zip_code', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'personal_id', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employee', 'email', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'email', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'personal_id', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'zip_code', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'country', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'state_province', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'city', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'address', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'last_name', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('employee', 'first_name', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
