"""Add company model

Revision ID: df8afbc693b9
Revises: 15509efef468
Create Date: 2022-08-25 17:00:56.055063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'df8afbc693b9'
down_revision = '15509efef468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(), nullable=False))
    op.add_column('company', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('company', sa.Column('city', sa.String(), nullable=False))
    op.add_column('company', sa.Column('state_province', sa.String(), nullable=False))
    op.add_column('company', sa.Column('country', sa.String(), nullable=False))
    op.add_column('company', sa.Column('zip_code', sa.String(), nullable=False))
    op.add_column('company', sa.Column('time_zone', sa.String(), nullable=True))
    op.add_column('company', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('company', sa.Column('owner_last_name', sa.String(), nullable=True))
    op.add_column('company', sa.Column('email', sa.String(), nullable=False))
    op.add_column('company', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('company', sa.Column('tax_id', sa.String(), nullable=False))
    op.alter_column(
        'company',
        'company_name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.drop_index('ix_company_id', table_name='company')
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=True)
    op.create_unique_constraint(None, 'company', ['email'])
    op.add_column('employee', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'avatar_url')
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.create_index('ix_company_id', 'company', ['id'], unique=False)
    op.alter_column(
        'company',
        'company_name',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.drop_column('company', 'tax_id')
    op.drop_column('company', 'phone_number')
    op.drop_column('company', 'email')
    op.drop_column('company', 'owner_last_name')
    op.drop_column('company', 'owner_name')
    op.drop_column('company', 'time_zone')
    op.drop_column('company', 'zip_code')
    op.drop_column('company', 'country')
    op.drop_column('company', 'state_province')
    op.drop_column('company', 'city')
    op.drop_column('company', 'address_line_2')
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
