---
extends: default

ignore: |
  **/pnpm-lock.yaml

rules:
  line-length:
    max: 100
    ignore: |
      **/workflows/lint.yml
      **/serverless.yml
      **/sls/envs/*.yml
  braces:
    max-spaces-inside: -1  # Disable spaces inside braces enforcement
    min-spaces-inside: -1  # Disable spaces inside braces enforcement
  truthy:
    ignore: |
      **/workflows/*.yml
