---
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env.local
    volumes:
      - ./app:/code/app
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
